### ISSUE TITLE
@rescript/core

### ISSUE THREAD

**Issue by whitchapman** [glennsl/rescript-fetch#3]
I see it has been 6 months since the last commit; is this project still active? Any plans to update this to use the just released @rescript/core? I am currently investigating fetch bindings for rescript, so I'd be happy to open a PR.

**Comment by glennsl** [comment]
Hi. I plan on updating it to use the new `promise` type alias and to show examples using the async/await syntax introduced in rescript 10.1. But none of those should be breaking changes, they just look cleaner. I haven't looked into @rescript/core and not sure what relevance it would have for these bindings.

**Comment by whitchapman** [comment]
Since `@ryyppy/rescript-promise` is incorporated as is into `@rescript/core`, and your code is not opening Belt, or even using it as far as I can tell, it should just be a matter of updating the dependency. Probably something you could easily do at the same time as your other planned changes. Thanks for the update!

**Comment by glennsl** [comment]
It shouldn't make any practical difference as they're both just aliases to `Js.Promise.t`. `rescript-promise` should really just have been a dev dependency here, as it's only really used for the examples. And it won't be needed at all with async/await, so I'll just remove it.

**Comment by glennsl** [comment]
Just released 0.2.0, which updates to rescript 10.1 in order to use the new `promise` type alias and async/await, and removes `rescript-promise` as a dependency.
