### ISSUE TITLE
Why does`Response.json` return a promise?

### ISSUE THREAD

**Issue by cristianoc** [glennsl/rescript-fetch#4]
```res
  @send external json: t => promise<Js.Json.t> = "json"
```

**Comment by glennsl** [comment]
Because the specification says so: https://fetch.spec.whatwg.org/#ref-for-dom-body-json%E2%91%A0

Do you have some indication that this is somehow wrong?

**Comment by cristianoc** [comment]
No was just surprised.
I was curious about use cases where it makes sense to await twice, but could not find any.
Not that it matters. The standard is the standard.
